automation:
  - alias: QuietCool Attic Fan Timer Finished
    id: quietcool_attic_fan_timer_finished
    mode: single
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.quietcool_attic_fan_timer
    action:
      - variables:
          finish_action: "{{ states('input_select.quietcool_timer_finish_action') }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ finish_action == 'Smart' }}"
            sequence:
              - service: button.press
                target:
                  entity_id: button.attic_exhaust_fan_start_quietcool_smart_mode
          - conditions:
              - condition: template
                value_template: "{{ finish_action == 'Off' }}"
            sequence:
              - service: button.press
                target:
                  entity_id: button.attic_exhaust_fan_stop_quietcool_fan
        default:
          - service: button.press
            target:
              entity_id: button.attic_exhaust_fan_start_quietcool_smart_mode

  - alias: QuietCool Whole House Fan Timer Finished
    id: quietcool_whole_house_fan_timer_finished
    mode: single
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.quietcool_whole_house_fan_timer
    action:
      - service: button.press
        target:
          entity_id: button.whole_house_fan_stop_quietcool_fan
